### PR TITLE
TransferFunction tutorial

### PR DESCRIPTION
**Pull request by usmanwardag**
Adds transfer function tutorial which demonstrates initialising `TransferFunction` objects, creating time and energy resolved responses, plotting them and using IO methods.

---
This change is [Reviewable](https://reviewable.io/reviews/stingraysoftware/notebooks/5)

### CODE REVIEW

**Comment by matteobachetti** [comment]
Why are some plots not appearing?

**Comment by usmanwardag** [comment]
I am setting `save=True` which means they are saved but not shown.

**Comment by matteobachetti** [comment]
Ah, ok. I would suggest to show at least in one case a 2-d transfer function, using both `save=True` and `save=False` in this case.

**Comment by usmanwardag** [comment]
Actually, this is dependent on PR #142 in stingray repository, where I added the option to show plots. Once, that is merged, I will modify this notebook.

**Comment by usmanwardag** [comment]
Added an example. For now, the data we have is quite trivial and it would make sense to add more illustrative examples later on.

**Comment by matteobachetti** [comment]
This looks good! Is it ready for merging?

**Comment by usmanwardag** [comment]
Yeah, I think it is.

**Pull request merged**
