### PR TITLE
Cross spectra tutorial

### PR DESCRIPTION
**Pull request by abigailStev**
Notebook with a tutorial on how to use Crossspectrum and AveragedCrossspectrum, and all the properties and built-in methods for manipulation.

---

This change is [Reviewable](https://reviewable.io/reviews/stingraysoftware/notebooks/6)

### CODE REVIEW

**Comment by dhuppenkothen** [comment]
I can't tell you how excited I am by this!

**Comment by abigailStev** [comment]
@dhuppenkothen @matteobachetti This is ready for review! It's up-to-date with the current functionality of the Crossspectrum class, as far as I can tell.

**Comment by abigailStev** [comment]
Although...the coherence looks a bit low in the final plot...

**Comment by abigailStev** [comment]
Hi @dhuppenkothen @matteobachetti I'm merging this now!

**Pull request merged**
