### PR TITLE
Added some text and fixed some bugs in modelling tutorial

### PR DESCRIPTION
**Pull request by dhuppenkothen**
I added some more text as @matteobachetti suggested in the last PR before it got merged (those suggested changes never made it into that branch), and also made it work with minor API changes in PR #245 in the stingray repo.

---
This change is [Reviewable](https://reviewable.io/reviews/stingraysoftware/notebooks/19)

### CODE REVIEW

**Comment by abigailStev** [comment]
There's a conflict in Modeling/ModelingExamples.ipynb

**Comment by dhuppenkothen** [comment]
Ugh, notebooks are the worst for Version control.

**Comment by dhuppenkothen** [comment]
I don't know how to fix this conflict. help @abigailStev @matteobachetti ?

**Comment by abigailStev** [comment]
I can try to take a look on Sunday

**Comment by matteobachetti** [comment]
Closing and reopening with fixed conflicts in  #34

**Pull request closed without merging**
