### PR TITLE
Adds simulator tutorial

### PR DESCRIPTION
**Pull request by usmanwardag**
Rearranges files in simulator folder, and adds a basic tutorial for simulator class.

---
This change is [Reviewable](https://reviewable.io/reviews/stingraysoftware/notebooks/3)

### CODE REVIEW

**Comment by matteobachetti** [comment]
Before merging, I would suggest two more things to be added to the tutorial:

- Saving to `EventList`

- Showing the X-ray lag after simulating with the impulse response.

**Comment by usmanwardag** [comment]
@matteobachetti I think this is ready for review.

**Comment by matteobachetti** [comment]
@usmanwardag In `Simulator Tutorial.ipynb`: you do something like
```
spectrum = np.fft.rfftfreq(sim.N, d=sim.dt)[1:]
lc = sim.simulate(spectrum)
plt.plot(lc)
```
I think this is not what you mean to do: you are giving an array of frequencies to `simulate`, without an actual spectrum!

**Comment by usmanwardag** [comment]
Yes, indeed. Corrected that.

**Comment by usmanwardag** [comment]
@matteobachetti I have made outputs visible for notebooks over both PRs.

**Pull request merged**
