### PR TITLE
notebook to accompany the stingray.modeling subpackage

### PR DESCRIPTION
**Pull request by dhuppenkothen**
A non-exhaustive notebook with examples relating to the `stingray.modeling` subpackage. 
I think this could use more explanations and examples, but it's a first step.

---
This change is [Reviewable](https://reviewable.io/reviews/stingraysoftware/notebooks/8)

### CODE REVIEW

**Comment by matteobachetti** [comment]
The `PSDLogLikelihood` class defined here gives inconsistent results with that defined in the library (just a minus sign difference)

**Comment by matteobachetti** [comment]
As a result, the phrase "should yield the largest log-likelihood" sounds incorrect, because the incorrect parameters give ~4800, the correct ones ~2400 :)

**Comment by evandromr** [comment]
Hi, Sorry for taking so long to have a look at this. Is the notebook supposed to be up-to-date with the master branch of stingray? Because I'm running into Errors:

on input cell number 35, parest.fit(..) results in: `TypeError: lpost must be a subclass of Posterior or LogLikelihoood.`

and on input cell number 49, parest.fit() doesn't accept `priors` as a keyword argument: `TypeError: fit() got an unexpected keyword argument 'priors' `

**Comment by dhuppenkothen** [comment]
@evandromr thanks for catching that! We made some last-minute API changes before merging the `modeling` sub-package that are not reflected in the notebook yet. I'll fix that tomorrow morning.

**Comment by matteobachetti** [comment]
Hey @dhuppenkothen, is this notebook ready to merge?

**Comment by dhuppenkothen** [comment]
oooh, good question. Will check that and get back to you.

**Comment by matteobachetti** [comment]
Cool! 
A few minor comments:
+ In the introduction, I suggest to add some words on why this approach is better than taking a QPO and fitting it with Xspec using chi^2 minimization
+ Text between [17] and [18]: "we can an optimization routine" (typo)
+ In the subsection "Likelihood ratios": Why are likelihood ratios important?

**Comment by matteobachetti** [comment]
@dhuppenkothen if you have time to make those small changes above, it's good, but we can merge it also in the current state. I think it's important to have it merged, anyway :)

**Comment by dhuppenkothen** [comment]
Eek. That was not supposed to get merged yet. I've found a bunch of bugs I'm currently dealing with.

**Comment by dhuppenkothen** [comment]
Oh well, I'll submit a new PR once the bugs are ironed out.

**Comment by matteobachetti** [comment]
There were people asking me about QPO searches... so I figured it was better to have it merged. Modifications can still be done!

**Pull request merged**
