### PR TITLE
Created Build_docs.yml

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
Issue from: #52
Initialized the Build_docs.yml file, will add the jobs as per requirements..

### CODE REVIEW

**Comment by matteobachetti** [comment]
The idea is that you have to create a build_docs job similar to the one already present in Stingray (check the corresponding files), with the only difference of downloading the git version of Stingray

**Review by AnonymousCodes911 — COMMENTED** [review]
@matteobachetti, Please review this at your earliest convenience, 
Thankyou

**Comment by matteobachetti** [comment]
@AnonymousCodes911 the yaml is invalid, there are comments that should not be there. Actions are not starting for this reason

**Comment by AnonymousCodes911** [comment]
@matteobachetti ,I have added the comments because I was unsure of the specific actions we are trying to run. Could you please provide more details on the actions we will be attempting to achieve?

**Pull request closed without merging**
