### PR TITLE
Fixes errors in Lighcurve tutorial notebook

### PR DESCRIPTION
**Pull request by haroonrashid235**
Fixes `Lightcurve `notebook errors. `Lightcurve` attributes `ncount `and `rebin_lightcurve` have been refactored to `n` and `rebin` respectively. This pull request solves these errors and makes tutorial up-to-date  with latest `Lightcurve `code. 

@matteobachetti Please Review and Merge.

---
This change is [Reviewable](https://reviewable.io/reviews/stingraysoftware/notebooks/9)

### CODE REVIEW

**Comment by matteobachetti** [comment]
@haroonrashid235 Thanks! 
Could you please execute once the whole notebook and commit, so that people looking at the repository can see the final plots and outputs without executing it?

**Comment by haroonrashid235** [comment]
@matteobachetti  I have executed notebook and it displays useful data and all plots. Please review.

**Comment by abigailStev** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stingraysoftware/notebooks/9#-:-Ki5_Bzm4GsoKxPwTkxZ:bnfp4nl)*

**Comment by abigailStev** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stingraysoftware/notebooks/9)*

**Pull request merged**
