### PR TITLE
EventList notebooks

### PR DESCRIPTION
**Pull request by usmanwardag**
Adds notebook for EventList usage.

---
This change is [Reviewable](https://reviewable.io/reviews/stingraysoftware/notebooks/4)

### CODE REVIEW

**Comment by usmanwardag** [comment]
@matteobachetti I have revised this notebook as per the recent changes.

**Comment by matteobachetti** [comment]
Small bug: note that the light curve obtained from simulated events is shifted by half bin. This is due to the use of `tstart=0`. The original light curve had the first bin at time `t[0]=0`, and this means that `tstart` was half a bin _before_, or -0.5. Could you try to see if changing this small detail aligns the simulated to the original light curve?

**Comment by usmanwardag** [comment]
Yeah, it does. Updated notebook.

**Comment by matteobachetti** [comment]
Merged

**Pull request merged**
