### PR TITLE
Notebooks for simulator sub-project

### PR DESCRIPTION
**Pull request by usmanwardag**
This pull-request will keep on adding notebooks throughout this project to discuss updates on various sub-modules.

---
This change is [Reviewable](https://reviewable.io/reviews/stingraysoftware/notebooks/2)

### CODE REVIEW

**Comment by matteobachetti** [comment]
Good! It works even better than I expected!

**Comment by usmanwardag** [comment]
Cool, I will modify the code and tests in stingray repo now.

**Comment by OrkoHunter** [comment]
@usmanwardag Can you please rebase this branch with #1 so as to reduce the repository size which might get inflated by the notebooks ?

**Comment by usmanwardag** [comment]
@OrkoHunter The idea was to keep notebooks for this part of project separate (and at one place) so that they can be easily referenced. I am not sure though how it would affect size if we were to re-base it with #1?

**Comment by OrkoHunter** [comment]
@usmanwardag Sorry for being vague but I just meant you to have [`.gitattributes`](https://github.com/StingraySoftware/notebooks/blob/master/.gitattributes) file in the branch. This helps in reducing the size created by the prompt numbers of the notebook in every commit.

**Comment by usmanwardag** [comment]
@OrkoHunter Done.

**Comment by usmanwardag** [comment]
@matteobachetti Done for all cases. Is there anything else before merging?

**Comment by matteobachetti** [comment]
Looks good fir now. Merging

**Pull request merged**
