### PR TITLE
Updated the Notebooks

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
Earlier we weren't importing AutoCorrelation in 17th Cell, thus it was returning an Error in the 18th cell

### CODE REVIEW

**Comment by matteobachetti** [comment]
@AnonymousCodes911 thanks for your PR!
At the moment, the diff is full of changes of output or minimal changes to plots, which bloat the git history without changing anything substantial. Would it be possible to actually limit the PR to the lines that changed in the notebook?

**Comment by AnonymousCodes911** [comment]
> @AnonymousCodes911 thanks for your PR! At the moment, the diff is full of changes of output or minimal changes to plots, which bloat the git history without changing anything substantial. Would it be possible to actually limit the PR to the lines that changed in the notebook?

I tried to address this issue locally too, but whenever i changed something in a cell, it returned a output, thus clogging the diff space, kindly guide me on how to just add the changes i make in the notebooks.

**Comment by matteobachetti** [comment]
@AnonymousCodes911 let's start from the easy ones: you re-executed many notebooks without changing anything (but producing a lot of output). You could just stash the changes to those notebooks (or checkout the version in `main`).
In the notebook that you actaully changed, you can make a git diff, find out the modification to the cell you made, open the notebook in a text editor and copy that change. 
There are some tools that should make the diffing more robust (i.e. avoiding images from the diff), like 
https://nbdime.readthedocs.io/en/latest/ 
but I never tried them

**Comment by AnonymousCodes911** [comment]
@matteobachetti, Thank you so much for the quick responses,  I'll try with the naive approach that you mentioned and if that doesn't work, i can migrate to the tools you provided.
Thankyou!

**Comment by AnonymousCodes911** [comment]
@matteobachetti, 
Thank you for being patient, I have made [another commit](https://github.com/StingraySoftware/notebooks/pull/78/commits/601ee993f686a0206a5d360d90f80c4372d70d09), please verify if we can work with this and then i can move on to the other notebooks.
Thankyou!

**Comment by matteobachetti** [comment]
@AnonymousCodes911 yes, that commit is good. Please don't forget to cleanup the PR from all commits involving notebooks that have not been changed

**Comment by AnonymousCodes911** [comment]
I pushed the final commit in the new [PR](https://github.com/StingraySoftware/notebooks/pull/79).
no notebooks showing any error , please verify the same.

Thank you for your time and consideration 

PS: This is closed in #79

**Pull request closed without merging**
