### PR TITLE
Fixed Notebooks DeadTime, Modeling,Window Functions

### PR DESCRIPTION
**Pull request by AnonymousCodes911**
-Fixed syntax errors/ value errors.
-ps.freq and ps.power had different lengths, so truncated one array to match the length.

### CODE REVIEW

**Comment by AnonymousCodes911** [comment]
@matteobachetti, 
I think this also closes #45 ?

**Review by matteobachetti — CHANGES_REQUESTED** [review]
Thanks @AnonymousCodes911! 
A couple of points that need to be addressed: 

1) the window_functions notebook still has a lot of plot changes without significant code change, it should be cleaned up
2) The modeling notebook should *not* need to filter a part of the array. If this is needed, it is a bug. I would avoid making this kind of change, which hides a possible bug and is not easily understandable from users reading the docs. Could you please eliminate this from the PR and open an Issue instead?
3) Also, please do not explain your changes with comments in the notebooks, these messages should appear in the commit messages instead!

**Comment by AnonymousCodes911** [comment]
@matteobachetti 
sorry for the inconvenience, can you please check it again?  
Thank you for your patience and understanding.

**Comment by matteobachetti** [comment]
@AnonymousCodes911 Almost there! So, I currently see five files changed, and the Window one still has a lot of output (and you reverted the correct change 😅). Also, there still are comments that should not be there. Please check the current version of the "Files changed" tab (press "Refresh" if needed) to see all the changes you are proposing.

**Comment by AnonymousCodes911** [comment]
about the Window_function file, locally on my desktop it shows only the error i wanted to fix, I dont understand why after committing, it piles up such a vast diff with changed images.

see this for reference: 
image

**Comment by matteobachetti** [comment]
@AnonymousCodes911 you have to make the diff with respect to our main, not your local copy. I suggest to clone the repo again in a separate directory, copy the window notebook, and make the small modification you are proposing in that one.  I will squash and merge to eliminate all the intermediate steps.

Otherwise, it might be quicker and cleaner to:
1) sync your fork's main with our current main, which has already slightly evolved since you started this PR.
2) create a new branch and add in the changes you made one by one (one commit per notebook changed, explaining the modification in the commit).

Please note that in the cross correlation notebook you fused two code lines:
```from stingray import AutoCorrelationdt = 0.001  # seconds```

**Comment by AnonymousCodes911** [comment]
I created another [PR](https://github.com/StingraySoftware/notebooks/pull/84)😅, hopefully now the things will be in line, and it ll be much cleaner.

**Pull request closed without merging**
